export const prblWorkflowList = [
    {
        id: 1,
        uuid: 'prbl-uuid-001',
        kode: 'PRBL-2027-KA-03',
        team: 'Divisi Pendidikan',
        bulan: 'Maret',
        bulanNum: 3,
        tahun: 2027,
        status: 'active' as const,
        currentStep: 'PRBL01',
        createdAt: '2027-03-16T08:00:00Z',
    },
    {
        id: 2,
        uuid: 'prbl-uuid-002',
        kode: 'PRBL-2027-KA-02',
        team: 'Divisi Pendidikan',
        bulan: 'Februari',
        bulanNum: 2,
        tahun: 2027,
        status: 'completed' as const,
        currentStep: 'PRBL05',
        createdAt: '2027-02-16T08:00:00Z',
    },
    {
        id: 3,
        uuid: 'prbl-uuid-003',
        kode: 'PRBL-2027-MG-03',
        team: 'Divisi MUGER',
        bulan: 'Maret',
        bulanNum: 3,
        tahun: 2027,
        status: 'active' as const,
        currentStep: 'PRBL02A',
        createdAt: '2027-03-16T08:00:00Z',
    },
    {
        id: 4,
        uuid: 'prbl-uuid-004',
        kode: 'PRBL-2027-DW-03',
        team: 'Divisi Dewasa',
        bulan: 'Maret',
        bulanNum: 3,
        tahun: 2027,
        status: 'active' as const,
        currentStep: 'PRBL04',
        createdAt: '2027-03-16T08:00:00Z',
    },
];

export const prblHistory = [
    { action: 'created', by: 'Sistem', role: 'System', at: '2027-03-16T08:00:00Z', table: 'prbl01_data' },
    { action: 'drafted', by: 'Rina Wijaya', role: 'Ketua', team: 'Divisi Pendidikan', at: '2027-03-18T10:00:00Z', table: 'prbl01_data' },
    { action: 'commented', by: 'Rina Wijaya', role: 'Ketua', team: 'Divisi Pendidikan', at: '2027-03-19T10:00:00Z', notes: 'Mohon info, realisasi konsumsi ada selisih Rp 50.000' },
    { action: 'commented', by: 'Sari Dewi', role: 'Bendahara Umum 1', team: 'Tim Bendahara Umum', at: '2027-03-19T14:00:00Z', notes: 'Selisih dikembalikan via refund di PRBL03' },
    {
        action: 'submitted',
        by: 'Rina Wijaya',
        role: 'Ketua',
        team: 'Divisi Pendidikan',
        at: '2027-03-20T14:00:00Z',
        table: 'prbl01_data',
    },
    {
        action: 'approved',
        by: 'Budi Santoso',
        role: 'Ketua Monev',
        team: 'Tim Monev',
        at: '2027-03-22T10:00:00Z',
        table: 'prbl02a_data',
        notes: 'Laporan narasi sudah baik',
    },
    {
        action: 'approved',
        by: 'Sari Dewi',
        role: 'Bendahara Umum 1',
        team: 'Tim Bendahara Umum',
        at: '2027-03-23T09:00:00Z',
        table: 'prbl02b_data',
        notes: 'Realisasi anggaran sesuai',
    },
    { action: 'drafted', by: 'Rina Wijaya', role: 'Ketua', team: 'Divisi Pendidikan', at: '2027-03-24T10:00:00Z', table: 'prbl03_data' },
    {
        action: 'submitted',
        by: 'Rina Wijaya',
        role: 'Ketua',
        team: 'Divisi Pendidikan',
        at: '2027-03-25T11:00:00Z',
        table: 'prbl03_data',
        files: ['bukti_refund_maret_2027.jpg', 'foto_nota_maret_2027_1.jpg'],
    },
];

export const prblComments = [
    {
        by: 'Rina Wijaya',
        role: 'Ketua',
        at: '2027-03-19T10:00:00Z',
        text: 'Mohon info, realisasi konsumsi ada selisih Rp 50.000',
    },
    {
        by: 'Sari Dewi',
        role: 'Bendahara Umum 1',
        at: '2027-03-19T14:00:00Z',
        text: 'Selisih dikembalikan via refund di PRBL03',
    },
];

export const prblSteps = [
    { code: 'PRBL01', label: 'Laporan', status: 'completed' as const },
    { code: 'PRBL02A', label: 'Narasi', status: 'completed' as const },
    { code: 'PRBL02B', label: 'Anggaran', status: 'completed' as const },
    { code: 'PRBL03', label: 'Refund', status: 'completed' as const },
    { code: 'PRBL04', label: 'Review', status: 'active' as const },
    { code: 'PRBL05', label: 'Final', status: 'pending' as const },
];

export const prbl01Kegiatan = [
    {
        id: 1,
        program: 'PERAYAAN TAHUNAN',
        programKode: 'PK-2027-003',
        kegiatan: 'Persiapan Perayaan Tahunan',
        bulan: 'Maret (3)',
        masalah: 'Vendor dekorasi cancel mendadak, perlu cari vendor baru',
        langkah: 'Koordinasi dengan vendor lain, berhasil deal 2 hari sebelum acara',
        harapan: 'Perlu database vendor cadangan untuk antisipasi',
        catatan: 'Kegiatan berjalan lancar meskipun ada kendala awal',
        kuisioner: [
            {
                id: 1,
                pertanyaan: 'Berapa jumlah peserta yang hadir dalam kegiatan?',
                tipe: 'Kuantitatif',
                satuan: 'orang',
                jawaban: '35',
            },
            {
                id: 2,
                pertanyaan: 'Apakah kegiatan sesuai dengan rencana?',
                tipe: 'Kualitatif',
                satuan: null,
                jawaban: 'Ya, sesuai dengan beberapa penyesuaian minor',
            },
        ],
        realisasi: [
            {
                kode: '04.02.10.01.01.003.001.001.2027.03.00',
                mata: 'Konsumsi',
                dicairkan: 750000,
                realisasi: 700000,
                komentar: 'Sisa 50rb',
            },
            {
                kode: '04.02.10.01.01.003.001.002.2027.03.00',
                mata: 'Alat peraga',
                dicairkan: 500000,
                realisasi: 500000,
                komentar: 'Terpakai semua',
            },
        ],
        subtotalDicairkan: 1250000,
        subtotalRealisasi: 1200000,
    },
    {
        id: 2,
        program: 'SEKOLAH MINGGU RUTIN',
        programKode: 'PK-2027-001',
        kegiatan: 'Pelaksanaan SM Bulan Maret',
        bulan: 'Maret (3)',
        masalah: '',
        langkah: '',
        harapan: 'Konsistensi guru hadir tepat waktu',
        catatan: 'Kegiatan berjalan normal',
        kuisioner: [
            {
                id: 3,
                pertanyaan: 'Berapa jumlah peserta yang hadir dalam kegiatan?',
                tipe: 'Kuantitatif',
                satuan: 'orang',
                jawaban: '28',
            },
        ],
        realisasi: [
            {
                kode: '04.02.10.01.01.001.001.001.2027.03.00',
                mata: 'Snack',
                dicairkan: 200000,
                realisasi: 200000,
                komentar: 'Terpakai semua',
            },
        ],
        subtotalDicairkan: 200000,
        subtotalRealisasi: 200000,
    },
];

export const prbl03RefundData = {
    rekeningTujuan: {
        nama: 'Finance Playground',
        nomor: '0881234501',
        bank: 'BCA',
    },
    nominalRefund: 50000,
    keterangan: 'Selisih dari konsumsi rapat persiapan',
    buktiTransfer: ['bukti_refund_maret_2027.jpg'],
    fotoNota: ['foto_nota_maret_2027_1.jpg', 'foto_nota_maret_2027_2.jpg'],
    selisihItems: [
        { kode: '04.02.10.01.01.003.001.001.2027.03.00', mata: 'Konsumsi', dicairkan: 750000, realisasi: 700000, selisih: 50000 },
        { kode: '04.02.10.01.01.003.001.002.2027.03.00', mata: 'Alat peraga', dicairkan: 500000, realisasi: 500000, selisih: 0 },
        { kode: '04.02.10.01.01.001.001.001.2027.03.00', mata: 'Snack', dicairkan: 200000, realisasi: 200000, selisih: 0 },
    ],
    totalDicairkan: 1450000,
    totalRealisasi: 1400000,
    totalSelisih: 50000,
};

export const prbl05FinalData = {
    team: 'Divisi Pendidikan',
    bulan: 'Februari',
    bulanNum: 2,
    tahun: 2027,
    dilaporkanOleh: 'Rina Wijaya (Ketua)',
    tanggalLaporan: '20 Feb 2027',
    narasiDisetujui: 'Budi Santoso (Ketua Monev)',
    tanggalNarasi: '22 Feb 2027',
    anggaranDisetujui: 'Sari Dewi (Bendahara Umum 1)',
    tanggalAnggaran: '23 Feb 2027',
    refundOleh: 'Rina Wijaya (Ketua)',
    tanggalRefund: '25 Feb 2027',
    reviewAkhir: 'Sari Dewi (Bendahara Umum 1)',
    tanggalReview: '27 Feb 2027',
    rekeningTim: {
        nama: 'Rina Wijaya',
        nomor: '0881234501',
        bank: 'BCA',
    },
    totalDicairkan: 1450000,
    totalRealisasi: 1400000,
    totalRefund: 50000,
    totalItem: 3,
};
